package com.rightnow.ws.wsdl.v1_2;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://pts-jantt1-training-191.rightnowdemo.com/cgi-bin/pts-jantt1-training-191.cfg/services/soap?wsdl",
  targetNamespace="urn:wsdl.ws.rightnow.com/v1_2", name="RightNowSyncService")
public class RightNowSyncService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("com.rightnow.ws.wsdl.v1_2.RightNowSyncService");
      URL baseUrl = RightNowSyncService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            RightNowSyncService.class.getResource("http://pts-jantt1-training-191.rightnowdemo.com/cgi-bin/pts-jantt1-training-191.cfg/services/soap?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://pts-jantt1-training-191.rightnowdemo.com/cgi-bin/pts-jantt1-training-191.cfg/services/soap?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://pts-jantt1-training-191.rightnowdemo.com/cgi-bin/pts-jantt1-training-191.cfg/services/soap?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://pts-jantt1-training-191.rightnowdemo.com/cgi-bin/pts-jantt1-training-191.cfg/services/soap?wsdl",
          e);
    }
  }

  public RightNowSyncService()
  {
    super(wsdlLocationURL,
          new QName("urn:wsdl.ws.rightnow.com/v1_2", "RightNowSyncService"));
  }

  public RightNowSyncService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="RightNowFedAuthSyncPort")
  public com.rightnow.ws.wsdl.v1_2.RightNowFedAuthSyncPort getRightNowFedAuthSyncPort()
  {
    return (com.rightnow.ws.wsdl.v1_2.RightNowFedAuthSyncPort) super.getPort(new QName("urn:wsdl.ws.rightnow.com/v1_2",
                                                                                       "RightNowFedAuthSyncPort"),
                                                                             com.rightnow.ws.wsdl.v1_2.RightNowFedAuthSyncPort.class);
  }

  @WebEndpoint(name="RightNowFedAuthSyncPort")
  public com.rightnow.ws.wsdl.v1_2.RightNowFedAuthSyncPort getRightNowFedAuthSyncPort(WebServiceFeature... features)
  {
    return (com.rightnow.ws.wsdl.v1_2.RightNowFedAuthSyncPort) super.getPort(new QName("urn:wsdl.ws.rightnow.com/v1_2",
                                                                                       "RightNowFedAuthSyncPort"),
                                                                             com.rightnow.ws.wsdl.v1_2.RightNowFedAuthSyncPort.class,
                                                                             features);
  }

  @WebEndpoint(name="RightNowSyncPort")
  public com.rightnow.ws.wsdl.v1_2.RightNowSyncPort getRightNowSyncPort()
  {
    return (com.rightnow.ws.wsdl.v1_2.RightNowSyncPort) super.getPort(new QName("urn:wsdl.ws.rightnow.com/v1_2",
                                                                                "RightNowSyncPort"),
                                                                      com.rightnow.ws.wsdl.v1_2.RightNowSyncPort.class);
  }

  @WebEndpoint(name="RightNowSyncPort")
  public com.rightnow.ws.wsdl.v1_2.RightNowSyncPort getRightNowSyncPort(WebServiceFeature... features)
  {
    return (com.rightnow.ws.wsdl.v1_2.RightNowSyncPort) super.getPort(new QName("urn:wsdl.ws.rightnow.com/v1_2",
                                                                                "RightNowSyncPort"),
                                                                      com.rightnow.ws.wsdl.v1_2.RightNowSyncPort.class,
                                                                      features);
  }
}
