package com.rightnow.ws.wsdl.v1_2;

import javax.xml.ws.WebServiceRef;

import weblogic.wsee.jws.jaxws.owsm.SecurityPoliciesFeature;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

public class TestGetContact
{
    private RightNowSyncPort rightNowSOAPService;
  @WebServiceRef
  private static RightNowSyncService rightNowSyncService;
  public TestGetContact(){
      RightNowSyncService rightNowSyncService= new RightNowSyncService();
      SecurityPoliciesFeature securityFeatures= new SecurityPoliciesFeature(new String[]{
          "oracle/wss_username_token_client_policy";
      })
  }

  public static void main(String [] args)
  {
    rightNowSyncService = new RightNowSyncService();
    RightNowSyncPort rightNowSyncPort = rightNowSyncService.getRightNowSyncPort();
    // Add your code to call the desired methods.
  }
}
